name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test_api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v3
    - name: Run Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose

  deploy_api:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: Production
    needs: [test_api]
    defaults:
      run:
        working-directory: api
    steps:
    - uses: shimataro/ssh-key-action@v2
      name: Add SSH key
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && make deploy-api && exit"