name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test_api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v3
    - name: Run Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
